[build]
  command = "npm run build:web"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "EXPO_PUBLIC_EMAIL_WEBHOOK_URL,EXPO_PUBLIC_SPONSOR_CHECKOUT_URL,EXPO_PUBLIC_SPONSOR_MODULE_CHECKOUT_URL,EXPO_PUBLIC_STRIPE_CONNECT_URL,EXPO_PUBLIC_STRIPE_CONNECT_SYNC_URL,EXPO_PUBLIC_PARTICIPANT_CHECKOUT_URL,EXPO_PUBLIC_ORGANIZER_COMPLIANCE_WEBHOOK_URL,EXPO_PUBLIC_ADMIN_CONTACT_EMAIL,EXPO_PUBLIC_SUPABASE_ANON_KEY,EXPO_PUBLIC_SUPABASE_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
